# Generated by Django 5.0.2 on 2024-02-15 22:45

from django.db import migrations

from teams.models import MANAGEMENT, SALES, SUPPORT


def create_teams(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    teams = apps.get_model("teams", "Team")
    for name in [MANAGEMENT, SALES, SUPPORT]:
        teams.objects.using(db_alias).create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_teams),
    ]
