# Generated by Django 5.0.1 on 2024-01-31 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contracts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("location", models.TextField(blank=True)),
                ("number_of_attendees", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PLANNED", "Planned"),
                            ("HELD", "Held"),
                            ("NOT HELD", "Not Held"),
                            ("NOT STARTED", "Not Started"),
                            ("STARTED", "Started"),
                            ("COMPLETED", "Completed"),
                            ("CANCELED", "Canceled"),
                        ],
                        default="PLANNED",
                        max_length=64,
                        null=True,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "contract",
                    models.OneToOneField(
                        limit_choices_to={"signed": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event",
                        to="contracts.contract",
                    ),
                ),
                (
                    "support_contact",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"team_id": 3},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "db_table": "event",
                "ordering": ("-created_date",),
            },
        ),
    ]
