# Generated by Django 5.0.1 on 2024-01-31 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "first_name",
                    models.CharField(
                        help_text="First name of the user", max_length=128
                    ),
                ),
                (
                    "last_name",
                    models.CharField(help_text="Last name of the user", max_length=128),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=25, null=True, unique=True),
                ),
                ("company", models.CharField(blank=True, max_length=128)),
                ("note", models.TextField(blank=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "sales_contact",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role_id": 2},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "db_table": "client",
                "ordering": ("-updated_date",),
            },
        ),
    ]
